DATASET:
    train_list: ['Human36M']
    test_list: ['Human36M']
    input_joint_set: 'human36'
    target_joint_set: 'human36'
    workers: 64
    use_gt_input: False

MODEL:
    name: 'GTRS_net'
    input_shape: [384, 288]
    normal_loss_weight: 0.1
    edge_loss_weight: 20
    joint_loss_weight: 0.001
    posenet_pretrained: True
    posenet_path: './experiment/pam_h36m'

TRAIN:
    print_freq: 80
    batch_size: 1024
    shuffle: True
    begin_epoch: 1
    end_epoch: 180
    edge_loss_start: 1
    scheduler: 'step'
    lr: 0.0001
    lr_step: [10,30,60,90,120,150]
    lr_factor: 0.9
    optimizer: 'adam'

AUG:
    flip: False
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False
