DATASET:
    train_list: ['Human36M', 'COCO', 'MuCo']
    test_list: ['PW3D']
    input_joint_set: 'coco'
    target_joint_set: 'human36'
    workers: 64
    use_gt_input: False

MODEL:
    name: 'GTRS_net'
    input_shape: [384, 288]
    normal_loss_weight: 0.1
    edge_loss_weight: 20
    joint_loss_weight: 0.0012
    posenet_pretrained: True
    posenet_path: './experiment/pam_3dpw'

TRAIN:
    print_freq: 80
    batch_size: 1024
    shuffle: True
    begin_epoch: 1
    end_epoch: 150
    edge_loss_start: 1
    scheduler: 'step'
    lr: 0.0001
    lr_step: [20,40,60,80]
    lr_factor: 0.95
    optimizer: 'adam'

AUG:
    flip: False
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False
